"""Write a literature-research paper report artifact bundle."""

from __future__ import annotations

import argparse
import sys

from ._writer import ArtifactWriterError, default_report_json, print_result, write_artifact


KIND = "paper_report"


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--artifact-dir", required=True, help="Target artifact directory")
    parser.add_argument("--turn-id", help="Optional local turn id; autogenerated if omitted")
    parser.add_argument("--query", required=True)
    parser.add_argument("--paper-count", required=True, type=int)
    parser.add_argument("--top-paper", action="append", default=[], dest="top_papers")
    parser.add_argument("--recommended-recipe", required=True)
    parser.add_argument("--summary", help="Override manifest summary")
    parser.add_argument("--title", help="Override artifact title")
    parser.add_argument("--tag", action="append", default=[], dest="tags")
    parser.add_argument("--raw-text")
    return parser


def render_markdown(query: str, paper_count: int, top_papers: list[str], recommended_recipe: str) -> str:
    lines = [
        f"# Paper Report: {query}",
        "",
        f"- Papers reviewed: {paper_count}",
        f"- Recommended recipe: {recommended_recipe}",
        "",
        "## Top Papers",
    ]
    if top_papers:
        lines.extend(f"- {paper}" for paper in top_papers)
    else:
        lines.append("- No specific papers recorded")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)

    try:
        metadata = {
            "query": args.query,
            "paper_count": args.paper_count,
            "top_papers": args.top_papers,
            "recommended_recipe": args.recommended_recipe,
        }
        title = args.title or f"Paper report for {args.query}"
        summary = args.summary or f"Reviewed {args.paper_count} papers for {args.query}"
        report_markdown = render_markdown(
            args.query,
            args.paper_count,
            args.top_papers,
            args.recommended_recipe,
        )
        report_json = default_report_json(metadata)
        result = write_artifact(
            artifact_dir=args.artifact_dir,
            turn_id=args.turn_id,
            kind=KIND,
            title=title,
            summary=summary,
            metadata=metadata,
            report_markdown=report_markdown,
            report_json=report_json,
            raw_text=args.raw_text,
            tags=args.tags or ["paper", "research"],
        )
    except ArtifactWriterError as error:
        parser.exit(status=2, message=f"error: {error}\n")

    print_result(result)
    return 0


if __name__ == "__main__":
    sys.exit(main())
