"""Write an HF jobs snapshot artifact bundle."""

from __future__ import annotations

import argparse
import sys

from ._writer import ArtifactWriterError, default_report_json, print_result, write_artifact


KIND = "job_snapshot"


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--artifact-dir", required=True, help="Target artifact directory")
    parser.add_argument("--turn-id", help="Optional local turn id; autogenerated if omitted")
    parser.add_argument("--job-id", required=True)
    parser.add_argument("--status", required=True)
    parser.add_argument("--hardware")
    parser.add_argument("--dashboard-url")
    parser.add_argument("--duration-seconds", type=int)
    parser.add_argument("--summary", help="Override manifest summary")
    parser.add_argument("--title", help="Override artifact title")
    parser.add_argument("--tag", action="append", default=[], dest="tags")
    parser.add_argument("--raw-text")
    return parser


def render_markdown(
    job_id: str,
    status: str,
    hardware: str | None,
    dashboard_url: str | None,
    duration_seconds: int | None,
) -> str:
    lines = [
        f"# Job Snapshot: {job_id}",
        "",
        f"- Status: {status}",
    ]
    if hardware:
        lines.append(f"- Hardware: {hardware}")
    if duration_seconds is not None:
        lines.append(f"- Duration (seconds): {duration_seconds}")
    if dashboard_url:
        lines.append(f"- Dashboard: {dashboard_url}")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)

    try:
        metadata = {
            "job_id": args.job_id,
            "status": args.status,
            "hardware": args.hardware,
            "dashboard_url": args.dashboard_url,
            "duration_seconds": args.duration_seconds,
        }
        title = args.title or f"Job snapshot for {args.job_id}"
        summary = args.summary or f"{args.job_id} is currently {args.status}"
        report_markdown = render_markdown(
            args.job_id,
            args.status,
            args.hardware,
            args.dashboard_url,
            args.duration_seconds,
        )
        report_json = default_report_json(metadata)
        result = write_artifact(
            artifact_dir=args.artifact_dir,
            turn_id=args.turn_id,
            kind=KIND,
            title=title,
            summary=summary,
            metadata=metadata,
            report_markdown=report_markdown,
            report_json=report_json,
            raw_text=args.raw_text,
            tags=args.tags or ["job", "hf"],
        )
    except ArtifactWriterError as error:
        parser.exit(status=2, message=f"error: {error}\n")

    print_result(result)
    return 0


if __name__ == "__main__":
    sys.exit(main())
